Add the hz tool to update the Thrift file method
CyanAsterisk/FreeCar pull request #84
Opened 2023-03-06 07:28 UTC by Nihilism0

#### What type of PR is this?
feat

#### Describe

Add the hz tool to update the Thrift file method

2023-03-06 08:09 UTC, L2ncE requested changes

2023-03-06 08:09 UTC, L2ncE commented on README.md
> +//If the update is a Thrift file
shell 中的注释用 #，然后应该加一个空格
eg.
```sh
# If the update is a proto file

2023-03-06 08:09 UTC, L2ncE commented on README.md
> +- The -I option is specially added for proto files
句号

2023-03-06 08:09 UTC, L2ncE commented on README_zh.md
> +hz update -idl ./../../idl/api.thrift
ditto

2023-03-06 08:09 UTC, L2ncE commented on README_zh.md
> +- 选项`-I`是专门为proto文件添加的
中文与英文之间应该有空格

2023-03-06 08:10 UTC, L2ncE commented
Hi，我没有看到代码逻辑上的更改，也许这个应该是 docs 而不是 feat。
btw，如果愿意的话可以帮助我们修改&添加一下 Makefile 吗

2023-03-06 08:25 UTC, Nihilism0 commented
> 嗨，我没有看到代码逻辑上的更改，也许这个应该是 docs 而不是 feat。顺便说一句，如果愿意的话可以帮助我们修改&添加一下 Makefile 吗

Yes

2023-03-07 01:05 UTC, L2ncE commented on Makefile
> +
Put it into /cmd/api

2023-03-07 13:07 UTC, L2ncE commented on server/cmd/api/Makefile
> +	hz update -idl ../../idl/api.proto
It doesn't seem to be correct. `api.proto` is still under the command `update-thrift`. This project should not have `api. thrift`. You can consider deleting it.

2023-03-07 13:10 UTC, L2ncE commented
看起来这个 PR 的标题也有问题，事实上我们这个项目并没有使用 hz & thrift IDL 的需求，但是更新操作确实是有问题的。这个 PR  希望可以是修复更新 api 的问题而不是新增一个对 thrift IDL 的操作

2023-03-08 01:30 UTC, L2ncE commented
hi, plz reslove conflict first

2023-03-08 10:44 UTC, L2ncE commented on server/cmd/api/Makefile
> +	hz update -I -idl ./../../idl/api.proto
Why delete them, resolve conflict doesn't mean delete others code...

2023-03-08 10:51 UTC, closed without merging